export const nationalities: any = {
  "Perú": 8,
  Afganistán: 13,
  Albania: 10,
  Argelia: 18,
  Andorra: 8,
  Angola: 9,
  "Arabia Saudita": 10,
  Argentina: 8,
  Armenia: 10,
  Australia: 9,
  Austria: 12,
  Azerbaiyán: 8,
  Bahamas: 9,
  Bahréin: 9,
  Bangladesh: 17,
  Barbados: 11,
  Bielorrusia: 14,
  Bélgica: 11,
  Belice: 7,
  Benín: 8,
  Bután: 11,
  Bolivia: 7,
  "Bosnia y Herzegovina": 13,
  Botsuana: 9,
  Brasil: 11,
  Brunéi: 7,
  Bulgaria: 10,
  "Burkina Faso": 13,
  Burundi: 12,
  Camboya: 9,
  Camerún: 13,
  Canadá: 12,
  "Cabo Verde": 9,
  Chad: 12,
  Chile: 9,
  China: 18,
  "Ciudad del Vaticano": 7,
  Colombia: 10,
  Comoras: 8,
  Congo: 9,
  "Corea del Sur": 13,
  "Costa de Marfil": 12,
  "Costa Rica": 9,
  Croacia: 11,
  Cuba: 11,
  Chipre: 8,
  Dinamarca: 10,
  Dominica: 7,
  Ecuador: 10,
  Egipto: 14,
  "El Salvador": 9,
  "Emiratos Árabes Unidos": 15,
  Eritrea: 10,
  "Estados Unidos": 9,
  Estonia: 11,
  Eswatini: 13,
  Etiopía: 13,
  Fiyi: 9,
  Finlandia: 11,
  Francia: 13,
  Gabón: 13,
  Gambia: 10,
  Georgia: 11,
  Alemania: 10,
  Ghana: 10,
  Grecia: 9,
  Granada: 8,
  Guatemala: 13,
  Guinea: 10,
  "Guinea-Bissau": 11,
  "Guinea Ecuatorial": 12,
  Guyana: 7,
  Haití: 10,
  Honduras: 13,
  Hungría: 12,
  Islandia: 10,
  "India": 12,
  Indonesia: 16,
  Irán: 10,
  Irak: 12,
  Irlanda: 9,
  "Islas Marshall": 7,
  Israel: 9,
  Italia: 16,
  Jamaica: 9,
  Japón: 12,
  Jordania: 10,
  Kazajstán: 12,
  Kenia: 8,
  Kiribati: 8,
  Kuwait: 12,
  Kirguistán: 14,
  Laos: 12,
  Letonia: 11,
  "Líbano": 9,
  Lesoto: 9,
  Liberia: 9,
  Libia: 12,
  Liechtenstein: 9,
  Lituania: 11,
  Luxemburgo: 13,
  "Macedonia del Norte": 13,
  Madagascar: 12,
  Malawi: 8,
  Malasia: 12,
  Maldivas: 10,
  Malí: 11,
  Malta: 9,
  Mauritania: 11,
  Mauricio: 14,
  "México": 18,
  Micronesia: 8,
  Moldavia: 13,
  Mónaco: 8,
  Mongolia: 9,
  Montenegro: 13,
  Marruecos: 9,
  Mozambique: 13,
  Myanmar: 10,
  Namibia: 9,
  Nauru: 7,
  Nepal: 12,
  Nicaragua: 9,
  Níger: 11,
  Nigeria: 11,
  Noruega: 11,
  "Nueva Zelanda": 9,
  Omán: 8,
  "Países Bajos": 9,
  Pakistán: 13,
  Palau: 8,
  Panamá: 8,
  "Papúa Nueva Guinea": 8,
  Paraguay: 8,
  Filipinas: 12,
  Polonia: 11,
  Portugal: 12,
  Qatar: 11,
  "Reino Unido": 10,
  "República Centroafricana": 13,
  "República Checa": 9, 
  "República Dominicana": 11,
  Rumania: 13,
  Rusia: 10,
  Ruanda: 16,
  "San Cristóbal y Nieves": 8,
  "Santa Lucía": 9,
  "San Vicente y las Granadinas": 8,
  Samoa: 7,
  "San Marino": 9,
  "Santo Tomé y Príncipe": 8,
  Senegal: 12,
  Serbia: 13,
  Seychelles: 8,
  "Sierra Leona": 10,
  Singapur: 9,
  Eslovaquia: 10,
  Eslovenia: 13,
  "Islas Salomón": 8,
  Somalia: 9,
  Sudáfrica: 13,
  España: 8,
  "Sri Lanka": 10,
  Sudán: 9,
  Surinam: 9,
  Suecia: 10,
  Suiza: 12,
  Siria: 11,
  Taiwán: 10,
  Tayikistán: 14,
  Tanzania: 11,
  Tailandia: 13,
  "Timor Oriental": 10,
  Togo: 10,
  Tonga: 8,
  "Trinidad y Tobago": 10,
  Túnez: 8,
  Turquía: 11,
  Turkmenistán: 8,
  Tuvalu: 7,
  Uganda: 14,
  Ucrania: 9,
  Uruguay: 7,
  Uzbekistán: 14,
  Vanuatu: 7,
  Venezuela: 10,
  Vietnam: 9,
  Yemen: 9,
  Yibuti: 8,
  Zambia: 11,
  Zimbabue: 10,
};

export const nationalitiesForSelect = Object.keys(nationalities)
  .map((n) => {
    return { key: n, value: n };
  });
