export enum Color {
    COLOR_BG_SURFACE_PRIMARY_DEFAULT = '#121226',
    COLOR_BG_SURFACE_PRIMARY_HOVER = '#1b1b38',
    COLOR_BG_SURFACE_PRIMARY_ACTIVE = '#0e0e20',
    COLOR_BG_SURFACE_PRIMARY_DISABLED = '#2e2e46',
    COLOR_BG_SURFACE_PRIMARY_CURRENT = '#000415',

    COLOR_BG_SURFACE_SECONDARY_DEFAULT = '#ffffff',
    COLOR_BG_SURFACE_SECONDARY_HOVER = '#f0f0f0',
    COLOR_BG_SURFACE_SECONDARY_ACTIVE = '#e0e0e0',
    COLOR_BG_SURFACE_SECONDARY_DISABLED = '#d1d1d1',

    // BACKGROUND FILL
    COLOR_BG_FILL_PRIMARY_DEFAULT = '#e5eaf2',
    COLOR_BG_FILL_PRIMARY_HOVER = '#d0d6e3',
    COLOR_BG_FILL_PRIMARY_ACTIVE = '#b0b8d4',
    COLOR_BG_FILL_PRIMARY_DISABLED = '#c0c6d5',

    COLOR_BG_FILL_SECONDARY_DEFAULT = '#2e2e2e',
    COLOR_BG_FILL_SECONDARY_HOVER = '#3a3a3a',
    COLOR_BG_FILL_SECONDARY_ACTIVE = '#4a4a4a',
    COLOR_BG_FILL_SECONDARY_DISABLED = '#5a5a5a',

    // BORDER COLOR
    COLOR_BORDER_PRIMARY_DEFAULT = '#27272a',
    COLOR_BORDER_PRIMARY_HOVER = '#3f3f46',
    COLOR_BORDER_PRIMARY_ACTIVE = '#1c1c1f',
    COLOR_BORDER_PRIMARY_DISABLED = '#9ca3af',

    COLOR_BORDER_SECONDARY_DEFAULT = '#ffffff',
    COLOR_BORDER_SECONDARY_HOVER = '#ffffff',
    COLOR_BORDER_SECONDARY_ACTIVE = '#ffffff',
    COLOR_BORDER_SECONDARY_DISABLED = '#ffffff',

    // TEXT COLOR
    COLOR_TEXT_PRIMARY_DEFAULT = '#6e91d6',
    COLOR_TEXT_PRIMARY_HOVER = '#567bbd',
    COLOR_TEXT_PRIMARY_ACTIVE = '#3e5ba3',
    COLOR_TEXT_PRIMARY_DISABLED = '#b1b7c9',

    COLOR_TEXT_SECONDARY_DEFAULT = '#ffffff',
    COLOR_TEXT_SECONDARY_HOVER = '#e5e5e5',
    COLOR_TEXT_SECONDARY_ACTIVE = '#cccccc',
    COLOR_TEXT_SECONDARY_DISABLED = '#a3a3a3',

    // ICON COLOR
    COLOR_ICON_PRIMARY_DEFAULT = '#6e91d6',
    COLOR_ICON_PRIMARY_HOVER = '#567bbd',
    COLOR_ICON_PRIMARY_ACTIVE = '#3e5ba3',
    COLOR_ICON_PRIMARY_DISABLED = '#b1b7c9',

    COLOR_ICON_SECONDARY_DEFAULT = '#ffffff',
    COLOR_ICON_SECONDARY_HOVER = '#e5e5e5',
    COLOR_ICON_SECONDARY_ACTIVE = '#cccccc',
    COLOR_ICON_SECONDARY_DISABLED = '#a3a3a3',

    TEST = '#FF0000',
}
